{{- if .Values.limitRange.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "app.fullname" . }}-limits
  namespace: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  limits:
    {{- toYaml .Values.limitRange.limits | nindent 4 }}
{{- end }}
