{{- if and .Values.namespace.name (eq .Release.Namespace .Values.namespace.name) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
{{- end }}
