{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        {{- toYaml .Values.networkPolicy.ingress.from | nindent 8 }}
      ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
  egress:
    - to:
        {{- toYaml .Values.networkPolicy.egress.to | nindent 8 }}
      ports:
        {{- toYaml .Values.networkPolicy.egress.ports | nindent 8 }}
{{- end }}
