{{- if eq .Values.app.type "statefulset" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "app.fullname" . }}-stateful
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "app.fullname" . }}-headless
  replicas: {{ .Values.statefulSet.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include "app.configChecksum" . }}
    spec:
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      securityContext:
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.statefulSet.image.repository }}:{{ .Values.statefulSet.image.tag }}"
          imagePullPolicy: {{ .Values.statefulSet.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
          envFrom:
            - configMapRef:
                name: {{ include "app.fullname" . }}-config
            - secretRef:
                name: {{ include "app.fullname" . }}-secret
          resources:
            {{- toYaml .Values.statefulSet.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.statefulSet.storage.mountPath }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          {{- toYaml .Values.statefulSet.storage.accessModes | nindent 10 }}
        storageClassName: {{ .Values.statefulSet.storage.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.statefulSet.storage.size }}
{{- end }}
